[ tiled ]
websocket_uri = "ws://s25idcdm.xray.aps.anl.gov:8020/api/v1/stream/single/raw"

[ data_management_stations.25IDC ]
username = "s25idcuser"
password = "fT3fK1s<SF}K`ICv^aoX"
station_name = "25IDC"
scheduling_uri = "https://xraydtn03.xray.aps.anl.gov:11337"
data_storage_uri = "https://xraydtn03.xray.aps.anl.gov:22237"
processing_uri = "https://s25idcdm.xray.aps.anl.gov:55536"
