name = "simple"
description = "Processing for a Bluesky scan that has no significant data processing needs"
version = 2
owner = "s25idcuser"
userAccount = "s25idcuser"

[ stages.010-START ]
command = "/bin/date +%Y%m%d%H%M%S"
outputVariableRegexList = ["(?P<timeStamp>.*)"]

[ stages.020-UPDATE ]
command = "/usr/bin/git -C ~s25idcuser/src/oaty-bar pull"

[ stages.030-FIT_FLUORESCENCE ]
command = "/APSshare/bin/pixi run --manifest-path ~s25idcuser/src/oaty-bar fit-fluorescence $run_uid --raw-profile oaty-bar --results-profile oaty-bar-results"

[ stages.040-EXPORT ]
command = "/APSshare/bin/pixi run --manifest-path ~s25idcuser/src/oaty-bar export-hdf $run_uid $target_folder --raw-profile oaty-bar --results-profile oaty-bar-results"
