name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  linting:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: v0.67.2
        cache: true
    - run: |
        pixi run lint
        pixi run format --check
        pixi run sort-imports --check
  type-checking:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    needs: "linting"
    timeout-minutes: 10
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: v0.67.2
        cache: true
    - run: |
        pixi run check-types
  unit-tests:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    needs: "linting"
    timeout-minutes: 10
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: v0.67.2
        cache: true
    - name: Tests
      run: |
        pixi run tests
  # make-docs:
  #   defaults:
  #     run:
  #       shell: bash -l {0}
  #   runs-on: ubuntu-latest
  #   needs: "linting"
  #   timeout-minutes: 10
  #   strategy:
  #     max-parallel: 5
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: prefix-dev/setup-pixi@v0.9.0
  #     with:
  #       pixi-version: v0.53.0
  #       cache: true
  #   - run: |
  #       pixi run make-docs
  release-tag:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [linting, type-checking, unit-tests]
    steps:
      - name: update-release-tag
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/release',
              sha: context.sha
            });
